In [1]:
import numpy as np


In [2]:
#make np array from python list
myarray=np.array([1,2,4,67])
myarray

array([ 1,  2,  4, 67])

In [3]:
#make np array from python list with dtype
myarray=np.array([1,2,4,67], np.int8)
myarray

array([ 1,  2,  4, 67], dtype=int8)

In [4]:
#make np array from python list with dtype 
#you can not use large int with int8 use large size like int32 , int64
myarray=np.array([1,2,4454583,67], np.int8)
myarray

array([  1,   2, -73,  67], dtype=int8)

In [5]:
#accessing one dim np array
myarray=np.array([1,2,4,67], np.int8)
myarray[0]

1

In [6]:
#two dim np array
myarray=np.array([[1,2,4,67]], np.int8)
myarray

array([[ 1,  2,  4, 67]], dtype=int8)

In [7]:
#accessing two dim np array
myarray=np.array([[1,2,4,67]], np.int8)
myarray[0,3]
#it will give error
#myarray[0,4]
#myarray[1,3]

67

In [8]:
#find the shape of np array 1 row 4 column
myarray.shape

(1, 4)

In [9]:
#find the type of np array 
myarray.dtype

dtype('int8')

In [10]:
#update element in np array
myarray[0,3]=5
myarray

array([[1, 2, 4, 5]], dtype=int8)

## Array creation : from other python structure

### From List

In [11]:
#From python list two dim np array
list_array=np.array([[0,1,2,3],[4,5,6,7]])
list_array

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [12]:
list_array.size

8

### From Dictionary

In [13]:
#From python dictionary two dim np array
#type 1
list_array=np.array([{0:"a",1:"b",2:"c"},{3:"d",4:"e",5:"e"}])
#type 2
list_array_1= np.array([{0,1,2},{3,4,5}])
list_array
#dtype=object is not recommended generally

array([{0: 'a', 1: 'b', 2: 'c'}, {3: 'd', 4: 'e', 5: 'e'}], dtype=object)

In [14]:
list_array_1

array([{0, 1, 2}, {3, 4, 5}], dtype=object)

In [15]:
list_array.size


2

In [16]:
list_array_1.size

2

In [17]:
list_array[0]

{0: 'a', 1: 'b', 2: 'c'}

In [18]:
list_array_1[0]

{0, 1, 2}

## Array creation : from numpy array creation object

### zeros np-array

In [25]:
zeros= np.zeros((4,5))
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [26]:
zeros.dtype

dtype('float64')

In [27]:
zeros.shape

(4, 5)

### ones np-array

In [29]:
ones = np.ones((2,2))
ones

array([[1., 1.],
       [1., 1.]])

### arange

In [35]:
rng= np.arange(15)
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [36]:
rng= np.arange(0,15)
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [37]:
rng= np.arange(1,15)
rng

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [38]:
rng.dtype

dtype('int32')

### linspace np-array

In [49]:
# from 1 to 5 equal 12 elements
lnspace= np.linspace(1,5,12)
lnspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [46]:
lnspace.shape

(12,)

In [50]:
lnspace= np.linspace(1,5,5)
lnspace

array([1., 2., 3., 4., 5.])

In [51]:
lnspace.dtype

dtype('float64')

### empty np-array

In [55]:
#np-array with random values
emp= np.empty((2,3))
emp

array([[ 3.48534787e-306,  3.78509484e-291, -4.29767374e-002],
       [ 3.76706347e-291,  3.72547309e-291,  3.01316092e-316]])

### empty_like np-array

In [57]:
#size and shap like old array with random values 
old_array=np.array([1,2,4,67])
emp_like= np.empty_like(old_array)
emp_like

array([         0, 1071644672,          0, 1072693248])

### identity np-array

In [58]:
# identity matrix
ide = np.identity(2)
ide

array([[1., 0.],
       [0., 1.]])

### reshaping

In [59]:
arr= np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
# reshap will not change original array
rshp_array=arr.reshape(2,5)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
rshp_array

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [68]:
#fllaten the array
rshp_array.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [67]:
rshp_array

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

# axis of np-array

In [69]:
x= np.array(([0,1,2],[3,4,5],[6,7,8]))
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [70]:
#0 axis is along row 1 axis is along coulumns
x.sum(axis=0)

array([ 9, 12, 15])

<img src="https://cdn-coiao.nitrocdn.com/CYHudqJZsSxQpAPzLkHFOkuzFKDpEHGF/assets/static/optimized/rev-4d1b478/wp-content/uploads/2018/11/numpy-arrays-have-axes.png">

In [71]:
x.sum(axis=1)

array([ 3, 12, 21])

# atributes and methods of np-array

In [74]:
arr= np.array(([1,2,3],[4,5,6],[7,1,0]))
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [75]:
#invert the array (transpose)
arr.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [76]:
# flat gives itrator
arr.flat

In [83]:
arr= np.array(([1,2,3],[4,5,6],[7,1,0]))
arr


array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [84]:
for i in arr.flat:
    print(i)

1
2
3
4
5
6
7
1
0


In [85]:
arr.ndim

2

In [86]:
arr.size

9

In [87]:
arr.nbytes

36

In [88]:
#method for giving index of max value
arr.argmax()

6

In [91]:
arr.argmax(axis=0)

array([2, 1, 1], dtype=int32)

In [93]:
arr.argmax(axis=1)

array([2, 2, 0], dtype=int32)

In [89]:
#method for giving index of max value
arr.argmin()

8

In [92]:
arr.argmin(axis=0)

array([0, 2, 2], dtype=int32)

In [90]:
arr.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int32)

In [95]:
arr.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int32)

In [96]:
arr.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]], dtype=int32)

# oprations on np-array

In [100]:
arr1= np.array(([1,2,3],[4,5,6],[7,1,0]))
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [99]:
arr2= np.array(([1,2,1],[4,0,6],[8,1,0]))
arr2

array([[1, 2, 1],
       [4, 0, 6],
       [8, 1, 0]])

In [101]:
arr_add=arr1+arr2

In [102]:
arr_add

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [103]:
#this is not possible in normal python list
a1=[1,2,3]
a2=[4,5,6]
a1+a2

[1, 2, 3, 4, 5, 6]

In [104]:
arr1*arr2

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [105]:
2*arr1

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14,  2,  0]])

In [106]:
np.sqrt(arr1)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [108]:
arr1.sum()

29

In [109]:
arr1.max()

7

In [110]:
arr1.min()

0

In [111]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [112]:
np.where(arr1>5)

(array([1, 2], dtype=int32), array([2, 0], dtype=int32))

In [113]:
arr1[1,2]

6

In [114]:
arr1[2,0]

7

In [115]:
type(np.where(arr1>5))

tuple

In [116]:
np.count_nonzero(arr1)

8

In [117]:
np.nonzero(arr1)

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int32),
 array([0, 1, 2, 0, 1, 2, 0, 1], dtype=int32))

# numpy is effcient 

In [119]:
import sys
py_ar= [1,2,54,4]

In [120]:
py_ar

[1, 2, 54, 4]

In [121]:
np_ar=np.array(py_ar)

In [122]:
np_ar

array([ 1,  2, 54,  4])

In [123]:
sys.getsizeof(1)*len(py_ar)

64

In [124]:
np_ar.itemsize

4

In [125]:
np_ar.size

4

In [126]:
np_ar.itemsize*np_ar.size

16

In [128]:
np_ar.tolist()

[1, 2, 54, 4]


<a href="https://docs.scipy.org/doc/numpy-1.6.0/reference/generated/numpy.ndarray.html">More methods and attributes</a>

In [1]:
import numpy as np
a= np.array([[6,7,8],[1,2,3],[9,3,2]])
#print numpy multi-dim  array
print(a)
print(a[1,2])
print(a[0:2,2])
print(a[-1])
print(a[-1,0:2])
print(a[:,1:3])

[[6 7 8]
 [1 2 3]
 [9 3 2]]
3
[8 3]
[9 3 2]
[9 3]
[[7 8]
 [2 3]
 [3 2]]


In [2]:
#itrate throgh row
for row in a:
    print(row)

[6 7 8]
[1 2 3]
[9 3 2]


In [3]:
for cell in a.flat:
    print(cell)

6
7
8
1
2
3
9
3
2


In [4]:
b = np.arange(6).reshape(3,2)
c = np.arange(6,12).reshape(3,2)
print(b)
print(c)

[[0 1]
 [2 3]
 [4 5]]
[[ 6  7]
 [ 8  9]
 [10 11]]


In [5]:
#V stacking like putting one box over to other
d= np.vstack((b,c))
print(d)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]


In [6]:
#H stacking like putting one box side by side
e= np.hstack((b,c))
print(e)

[[ 0  1  6  7]
 [ 2  3  8  9]
 [ 4  5 10 11]]


In [7]:
f = np.arange(30).reshape(2,15)
print(f)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]]


In [8]:
#v slicing
g=np.hsplit(f,3)
print(g)
print(g[0])
print(g[1])
print(g[2])

[array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]]), array([[ 5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24]]), array([[10, 11, 12, 13, 14],
       [25, 26, 27, 28, 29]])]
[[ 0  1  2  3  4]
 [15 16 17 18 19]]
[[ 5  6  7  8  9]
 [20 21 22 23 24]]
[[10 11 12 13 14]
 [25 26 27 28 29]]


In [9]:
#h slicing
h=np.vsplit(f,2)
print(h)
print(h[0])
print(h[1])

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]]), array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])]
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]]
[[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]]


In [10]:
i = np.arange(12)
print(i)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [11]:
j=np.arange(12).reshape(3,4)
print(j)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [12]:
k= j>4
print(k)

[[False False False False]
 [False  True  True  True]
 [ True  True  True  True]]


In [13]:
#all elements greter than 4
l=j[k]
print(l)

[ 5  6  7  8  9 10 11]


In [14]:
#replace elements greter than 4 with -1
j[k]=-1
print(j)

[[ 0  1  2  3]
 [ 4 -1 -1 -1]
 [-1 -1 -1 -1]]


In [23]:
#nditer 
import numpy as np

a= np.arange(12).reshape(3,4)
for row in a:
    for cell in row:
        print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


In [24]:
import numpy as np

a= np.arange(12).reshape(3,4)
for row in a:
    print(row)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [27]:
a= np.arange(12).reshape(3,4)
for row in a:
    for cell in row:
        print(cell)
    

0
1
2
3
4
5
6
7
8
9
10
11


In [28]:
a= np.arange(12).reshape(3,4)
for cell in a.flatten():
        print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


In [29]:
for x in np.nditer(a,order="C"):
    print(x)

0
1
2
3
4
5
6
7
8
9
10
11


In [30]:
for x in np.nditer(a,order="F"):
    print(x)

0
4
8
1
5
9
2
6
10
3
7
11


In [31]:
for x in np.nditer(a,order="F",flags=['external_loop']):
    print(x)

[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]
